Repository AY2021S1-CS2103T-T13-3/tp, pull requests merged in 2020-10, with the labels that each got.

#77 Change UI to display 3 sections
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/client/ViewClientCommand.java
  src/main/java/seedu/address/ui/ClientInfoPage.java
  src/main/java/seedu/address/ui/ClientListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RightSideBar.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/images/default-profile-picture.jpg
  src/main/resources/view/ClientInfoPage.fxml
  src/main/resources/view/ClientListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RightSideBar.fxml
Labels: status.ToReview

#80 Add session
  src/main/java/seedu/address/logic/commands/client/AddClientCommand.java
  src/main/java/seedu/address/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/session/AddSessionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/client/AddClientCommandParser.java
  src/main/java/seedu/address/logic/parser/client/CliSyntax.java
  src/main/java/seedu/address/logic/parser/client/DeleteClientCommandParser.java
  src/main/java/seedu/address/logic/parser/client/EditClientCommandParser.java
  src/main/java/seedu/address/logic/parser/client/FindClientCommandParser.java
  src/main/java/seedu/address/logic/parser/client/ViewClientCommandParser.java
  src/main/java/seedu/address/logic/parser/session/AddSessionCommandParser.java
  src/main/java/seedu/address/logic/parser/session/CliSyntax.java
  src/main/java/seedu/address/logic/parser/session/SessionParserUtil.java
  src/main/java/seedu/address/model/session/Interval.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedSession.java
  src/test/java/seedu/address/logic/commands/client/ClientCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/session/AddSessionCommandTest.java
  src/test/java/seedu/address/logic/commands/session/SessionCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/session/AddSessionCommandParserTest.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/SessionBuilder.java
  src/test/java/seedu/address/testutil/TypicalClients.java
  src/test/java/seedu/address/testutil/TypicalSessions.java
Labels: status.ToReview

#79 Remove address and email, add nextSession placeholder to client card
  src/main/java/seedu/address/ui/ClientCard.java
  src/main/resources/view/ClientListCard.fxml
Labels: status.ToMerge

#87 [UI] Add padding to tags
  src/main/resources/view/ClientInfoPage.fxml
  src/main/resources/view/DarkTheme.css
Labels: status.ToMerge

#91 Reschedule client to another session
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/schedule/RescheduleCommand.java
  src/main/java/seedu/address/logic/commands/session/EditSessionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/schedule/RescheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/session/EditSessionCommandParser.java
  src/main/java/seedu/address/model/session/Session.java
  src/test/java/seedu/address/logic/commands/client/ClientCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/schedule/RescheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/RescheduleDescriptorTest.java
  src/test/java/seedu/address/logic/commands/schedule/RescheduleTestUtil.java
  src/test/java/seedu/address/logic/commands/session/EditSessionCommandTest.java
  src/test/java/seedu/address/logic/commands/session/EditSessionDescriptorTest.java
  src/test/java/seedu/address/logic/commands/session/SessionCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/session/EditSessionCommandParserTest.java
  src/test/java/seedu/address/testutil/EditSessionDescriptorBuilder.java
  src/test/java/seedu/address/testutil/RescheduleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/SessionBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalSessions.java
Labels: status.needHelp

#94 New Homepage
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/Homepage.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/fitness_mascot.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Homepage.fxml
  src/test/java/seedu/address/logic/commands/HomeCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.enhancement

#95 Modify session identifier into Interval
  src/main/java/seedu/address/logic/commands/session/EditSessionCommand.java
  src/main/java/seedu/address/logic/parser/session/AddSessionCommandParser.java
  src/main/java/seedu/address/logic/parser/session/EditSessionCommandParser.java
  src/main/java/seedu/address/logic/parser/session/SessionParserUtil.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/main/java/seedu/address/storage/JsonAdaptedSession.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
Labels: status.ToReview

#96 Add functionality: Deschedule command
  src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/schedule/DeleteScheduleCommandParser.java
  src/main/java/seedu/address/model/schedule/SameSchedulePredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/test/java/seedu/address/logic/commands/schedule/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/ScheduleCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/schedule/DeleteScheduleCommandParserTest.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: status.ToReview

#97 Delete session command
  src/main/java/seedu/address/logic/commands/session/DeleteSessionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/session/DeleteSessionCommandParser.java
  src/main/java/seedu/address/model/session/IntervalContainsDatetimePredicate.java
  src/test/java/seedu/address/logic/commands/session/DeleteSessionCommandTest.java
  src/test/java/seedu/address/logic/commands/session/SessionCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/session/DeleteSessionCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalSessions.java
Labels: status.ToReview

#99 Minor fixes
  README.md
  build.gradle
  copyright.txt
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/HomeCommand.java
  src/main/java/seedu/address/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/address/logic/commands/schedule/RescheduleCommand.java
  src/main/java/seedu/address/logic/commands/session/EditSessionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/CheckExisting.java
  src/main/java/seedu/address/model/UniqueList.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/schedule/SameSchedulePredicate.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/session/Session.java
  src/main/java/seedu/address/ui/ClientInfoPage.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/Homepage.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/calendar.png
  src/main/resources/images/muscle.png
  src/main/resources/images/profile_info.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/Homepage.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/commands/client/AddClientCommandTest.java
  src/test/java/seedu/address/logic/commands/client/ViewClientCommandTest.java
  src/test/java/seedu/address/logic/commands/session/AddSessionCommandTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
Labels: status.ToReview

#109 Add editSession and Reschedule tests
  src/main/java/seedu/address/logic/commands/schedule/RescheduleCommand.java
  src/test/java/seedu/address/logic/commands/client/EditClientCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/RescheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/ScheduleCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/session/EditSessionCommandTest.java
  src/test/java/seedu/address/logic/commands/session/EditSessionDescriptorTest.java
  src/test/java/seedu/address/logic/commands/session/SessionCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/session/EditSessionCommandParserTest.java
  src/test/java/seedu/address/testutil/EditSessionDescriptorBuilder.java
  src/test/java/seedu/address/testutil/RescheduleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/SessionBuilder.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
  src/test/java/seedu/address/testutil/TypicalSessions.java
Labels: status.ToReview

#133 Update reschedule to editschedule
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/schedule/CliSyntax.java
  src/main/java/seedu/address/logic/parser/schedule/EditScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/schedule/RescheduleCommandParser.java
  src/test/java/seedu/address/logic/commands/schedule/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/schedule/EditScheduleDescriptorTest.java
  src/test/java/seedu/address/logic/commands/schedule/EditScheduleTestUtil.java
  src/test/java/seedu/address/logic/commands/schedule/ScheduleCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/session/DeleteSessionCommandIntegrationTest.java
  src/test/java/seedu/address/logic/parser/schedule/EditScheduleCommandParserTest.java
  src/test/java/seedu/address/testutil/EditScheduleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/RescheduleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: status.ToReview

#134 Added header for right side bar
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RightSideBar.java
  src/main/resources/view/RightSideBar.fxml
Labels: status.ToReview

#138 SessionList title bug
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RightSideBar.java
Labels: status.ToReview

#148 Bug fix: Detect file modification
  src/main/java/seedu/address/logic/commands/session/ViewSessionCommand.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: type.bug

#147 Bug fixes: assertion error in homepage and ug open 2 tabs
  src/main/java/seedu/address/logic/commands/session/ViewSessionCommand.java
  src/main/java/seedu/address/logic/parser/session/ViewSessionCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/Homepage.java
  src/test/java/seedu/address/logic/commands/session/SessionCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/session/ViewSessionCommandTest.java
  src/test/java/seedu/address/logic/parser/session/ViewSessionCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalSessions.java
Labels: status.ToReview, type.bug

#151 Update UGDG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/ClientPanel.png
  docs/images/SchedulePanel.png
  docs/images/SessionPanel.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
  docs/images/autocomplete_sample.png
  docs/images/cview_sample.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  docs/images/homepage.png
Labels: type.documentation

#149 Update Storage diagram, DG for Add and Delete Schedule
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddScheduleActivityDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/style.puml
  docs/diagrams/tracing/AddScheduleSequenceDiagram.puml
  docs/diagrams/tracing/OverlappingScheduleObjectDiagram0.puml
  docs/diagrams/tracing/OverlappingScheduleObjectDiagram1.puml
  docs/images/AddScheduleActivityDiagram.png
  docs/images/AddScheduleSequenceDiagram.png
  docs/images/OverlappingScheduleObjectDiagram0.png
  docs/images/OverlappingScheduleObjectDiagram1.png
  src/main/java/seedu/address/logic/commands/schedule/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/schedule/DeleteScheduleCommand.java
Labels: type.documentation

#170 Fix method for updating Session List title and change default GUI size
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/ui/RightSideBar.java
Labels: type.bug

#226 [PED] Overlapping session bug and update UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/schedule/EditScheduleCommand.java
  src/main/java/seedu/address/logic/commands/session/EditSessionCommand.java
Labels: priority.high, type.bug, type.documentation
