Repository AY2021S1-CS2103T-T13-3/tp, pull requests merged in 2020-09, with the labels that each got.

#44 Update AboutUs
  docs/AboutUs.md
Labels: status.ToMerge

#48 Update links in DG
  docs/DeveloperGuide.md
Labels: documentation, status.ToMerge

#56 Refactor DeleteCommand to DeleteClientCommand and update DG
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/client/DeleteClientCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/client/DeleteClientCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteClientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteClientCommandParserTest.java
Labels: status.ToMerge

#55 Refactor ListCommand to ListClientCommand and update DG
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/client/ListClientCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListClientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: status.ToMerge

#50 Update product scope, non-functional requirements, and glossary for v1.1
  docs/DeveloperGuide.md
Labels: documentation, status.ToMerge

#53 Add EditClientCommand feature and update its developer guide
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/client/EditClientCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditClientCommandParser.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditClientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditClientCommandParserTest.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
Labels: status.ToMerge

#46 Repurpose tags feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/client/AddClientCommand.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateClientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalClientsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditClientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditClientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedClientTest.java
  src/test/java/seedu/address/testutil/TypicalClients.java
Labels: status.ToReview

#57 Update DG
  docs/DeveloperGuide.md
Labels: status.ToReview

#59 Update DG - Tag a Client
  docs/DeveloperGuide.md
Labels: documentation, status.ToReview

#60 View Client Profile in a separate window, Update UG, DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/cview_sample.png
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/client/ViewClientCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/client/ViewClientCommandParser.java
  src/main/java/seedu/address/ui/ClientInfoPage.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/anonymous_128x128.png
  src/main/resources/images/profile_info.png
  src/main/resources/view/ClientInfoPage.fxml
  src/test/java/seedu/address/logic/commands/ViewClientCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewClientCommandParserTest.java
Labels: status.ToMerge
